message: Default profile activated.
spring:
  profiles:
    active: test
  h2:
    console:
      enabled: true
      path: /h2db
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    initialization-mode: always
    data: classpath:/data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
jwt:
  token:
    secret: bilogorscha
    expired: 3600000